default: &default
  adapter: postgresql
  hostname: localhost
  encoding: unicode
  username: riaznvirani
  password: password1
  pool: 5

development:
  <<: *default
  database: topictracker_development

test:
  <<: *default
  database: topictracker_test
